#!/bin/bash
#############################################################
# Const Vars
#############################################################
DEFAULTINSTALLDIR="/opt/raspadmin"
DEFAULTPORT="443"
CONFIGDIR="/etc/raspadmin"

#############################################################
# Functions
#############################################################
function get_boolean_value {
    mess=$(expr substr $1 1 1)
    if [ "$mess" == "y" ] || [ "$mess" == "Y" ] ; then
        echo -n "1"
    else
        echo -n "0"
    fi
}

function read_ini_file {
    inifile=$1
    pattern=$2
    [[ ! -f $inifile ]] && return 
    result=$(grep $pattern $inifile | cut -d'=' -f2)
    echo $result
}



#############################################################
# Checking requirements
#############################################################
clear
echo "---------------------------------------------"
echo "Welcome to raspadmin installer"
echo "---------------------------------------------"
echo ""
echo -e " Checking requirements : \e[34mIn progress\e[0m"
echo -e " Configuration         : \e[91mWaiting\e[0m"
echo -e " Copying files         : \e[91mWaiting\e[0m"
echo ""
echo ""
echo "----- Package configuration"
echo ""

if [ "$(whoami)" != "root" ] ; then
	echo "######### Error, you need to be root to execute this script"
	echo " Please use sudo"
	exit 2	

fi


dpkg -s python-pip > /dev/null 2>&1
pip=$?

dpkg -s python-dev > /dev/null 2>&1
dev=$?

if [ "$pip" == "1" ]; then
	echo "Installing pip"
	apt-get install -y python-pip
fi

if [ "$dev" == "1" ]; then
        echo "Installing python-dev"
        apt-get install -y python-dev

fi

echo "Installing needed libraries via pip"
pip --quiet install quik
pip --quiet install netifaces
pip --quiet install RPi.GPIO
pip --quiet install psutil
pip --quiet install requests

#############################################################
# Asking question
#############################################################
clear
echo "---------------------------------------------"
echo "Welcome to raspadmin installer"
echo "---------------------------------------------"
echo ""
echo -e " Checking requirements : \e[92mDone\e[0m"
echo -e " Configuration         : \e[34mIn progress\e[0m"
echo -e " Copying files         : \e[91mWaiting\e[0m"
echo ""
echo "Please answer few questions for the installation process"
echo ""
echo "----- Directory configuration"
echo ""

NO_CONSTRAINTS="y;Y;n;N;No;NO;no;yes;Yes;YEs;YES"
installdir=""

if [ -f /etc/raspadmin/raspadmin.conf ] ; then
		installdir=$(read_ini_file "/etc/raspadmin/raspadmin.conf" "staticfiledir" | sed -e "s/static//g")
fi

if [ "$installdir" == "" ] ; then
	installdir=$DEFAULTINSTALLDIR
	port=$DEFAULTPORT
	[[ ! -d $CONFIGDIR ]] && mkdir $CONFIGDIR

	 ssl=yes
        openssl genrsa  -out $CONFIGDIR/cert.key 1024
        openssl req -subj '/C=XX/ST=YY/L=ZZ/CN=VV' -new -key $CONFIGDIR/cert.key -out $CONFIGDIR/cert.csr
        openssl x509 -req -days 4000 -in $CONFIGDIR/cert.csr -signkey $CONFIGDIR/cert.key -out $CONFIGDIR/cert.crt
        rm -f $CONFIGDIR/cert.csr
        certificate_path="$CONFIGDIR/cert.crt"
        key_path="$CONFIGDIR/cert.key"

#	ssl="no"
#	certificate_path=""
#	key_path=""


	
	sed -e "s#\$PORT#$port#" -e "s#\$INSTALLDIR#$installdir#" -e "s#\$CERT#$certificate_path#" -e "s#\$KEY#$key_path#" -e "s#\$SSL#$ssl#"  conf/raspadmin.conf > $CONFIGDIR/raspadmin.conf

fi


clear
echo "---------------------------------------------"
echo "Welcome to raspadmin installer"
echo "---------------------------------------------"
echo ""
echo -e " Checking requirements : \e[92mDone\e[0m"
echo -e " Configuration         : \e[92mDone\e[0m"
echo -e " Copying files         : \e[34mWaiting\e[0m"
echo ""
echo "----- Installation"
echo ""

[[ -d /var/log/raspadmin ]] || mkdir /var/log/raspadmin

echo ""
echo "----- File copy"
[[ -d "$installdir" ]] ||  mkdir $installdir
cp -R sources/* $installdir

echo "----- Right management"
chown -R root:root $installdir
chmod -R 770 $installdir
chmod +x /etc/init.d/raspadmin
chmod 770 /var/log/raspadmin

echo "----- StartUp "
sed -e "s#\$INSTALLDIR#$installdir#" init/raspadmin > /etc/init.d/raspadmin
chmod 755 /etc/init.d/raspadmin
update-rc.d raspadmin defaults
echo ""

clear
echo "---------------------------------------------"
echo "Welcome to raspadmin installer"
echo "---------------------------------------------"
echo ""
echo -e " Checking requirements : \e[92mDone\e[0m"
echo -e " Configuration         : \e[92mDone\e[0m"
echo -e " Copying files         : \e[92mDone\e[0m"
echo ""
echo " To start the application : sudo service raspadmin start"
echo " To install modules (NAS, pyload, gateone, ...), proceed as following :"
echo "   * cd modules"
echo "   * sudo ./installer"
echo ""
echo " Please read information about this module in the wiki page of this project"
echo " https://github.com/air01a/raspadmin/wiki/Module"


